/*
 * Copyright (c) 2024, Yaya Kamissokho
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.yayakm.config;

import io.github.yayakm.util.Length;

/**
 * Represents various properties of an automaton, including state count, finiteness,
 * and expected text size generated by the automaton.
 *
 * @author yaya.kamissokho@gmail.com
 */
public class AutomatonProperties {
    private final int numberOfStates;
    private final boolean isFinite;
    private final int generatedTextExpectedMinSize;
    private final int generatedTextExpectedMaxSize;

    /**
     * Constructs AutomatonProperties with detailed length specifications.
     *
     * @param numberOfStates the total number of states in the automaton
     * @param isFinite       whether the automaton is finite
     * @param length         the length object containing expected minimum and maximum sizes of generated text
     */
    public AutomatonProperties(int numberOfStates, boolean isFinite, Length length) {
        this.numberOfStates = numberOfStates;
        this.isFinite = isFinite;
        this.generatedTextExpectedMinSize = length.getMin();
        this.generatedTextExpectedMaxSize = length.getMax();
    }

    /**
     * Constructs AutomatonProperties without detailed length specifications.
     *
     * @param numberOfStates the total number of states in the automaton
     * @param isFinite       whether the automaton is finite
     */
    public AutomatonProperties(int numberOfStates, boolean isFinite) {
        this(numberOfStates, isFinite, new Length(0, 0));  // Assume default lengths if not provided
    }

    public int getNumberOfStates() {
        return numberOfStates;
    }

    public boolean isFinite() {
        return isFinite;
    }

    public int getGeneratedTextExpectedMinSize() {
        return generatedTextExpectedMinSize;
    }

    public int getGeneratedTextExpectedMaxSize() {
        return generatedTextExpectedMaxSize;
    }

    @Override
    public String toString() {
        return String.format("Number of States: %d, Is Finite: %b, Expected Min Size: %d, Expected Max Size: %d",
                numberOfStates, isFinite, generatedTextExpectedMinSize, generatedTextExpectedMaxSize);
    }
}
